# Generated by Django 3.1.1 on 2020-09-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adoptante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_pat', models.CharField(max_length=20)),
                ('apellido_mat', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.PositiveSmallIntegerField()),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('vacunas', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[('AD', 'Adoptado'), ('IG', 'Ingresado'), ('RI', 'Reingresado')], default='IG', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_pat', models.CharField(max_length=20)),
                ('apellido_mat', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vac', models.CharField(max_length=20, unique=True)),
                ('descripcion_vac', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mascota_vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='historial_mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.adoptante')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
            ],
        ),
    ]
