# Generated by Django 3.1.1 on 2020-09-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='vacunas',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='status',
            field=models.CharField(choices=[('AD', 'Adoptado'), ('IG', 'Ingresado'), ('RI', 'Reingresado')], default='IG', max_length=2),
        ),
    ]
